spring.datasource.url=jdbc:mysql://localhost:3306/schooldiary
spring.datasource.username=root
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

cloudinary.cloud-name=cnvywfvo
cloudinary.api-key=745526227391412
cloudinary.api-secret=W4FLONCmoEVMVOT2fuP12dzAbVg